version: '3.7'

services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - db
    container_name: api
    command: sh -c "npx sequelize-cli db:seed:all"
    #entrypoint: ./wait-for-it.sh db
    environment:
      DB_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://username:postgres@db:5432/postgres
    restart: always
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: client
    #depends_on:
    #  - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always